export const alphabets = [
	"क",
	"ख",
	"ग",
	"घ",
	"ङ",
	"च",
	"छ",
	"ज",
	"झ",
	"ञ",
	"ट",
	"ठ",
	"ड",
	"ढ",
	"ण",
	"त",
	"थ",
	"द",
	"ध",
	"न",
	"प",
	"फ",
	"ब",
	"भ",
	"म",
	"य",
	"र",
	"ल",
	"व",
	"श",
	"ष",
	"स",
	"ह",
	"क्ष",
	"त्र",
	"ज्ञ",
	"अ",
	"उ",
	"इ",
	"ए",
	"ऐ",
];

export const songs = {
	क: [
		{
			title: "Wajah tum ho",
			start: "27",
			primaryColor: "#ff0000c2",
			source: "https://www.youtube.com/embed/UF9kvy51_F0",
			startPhrase: "Kaise kahu...",
		},
		{
			title: "Kya mujhe pyaar hai",
			start: "39",
			primaryColor: "#ff9900c2",
			source: "https://www.youtube.com/embed/XPu9ZE4Onzc",
			startPhrase: "Kyu ajj kal...",
		},
		{
			title: "Jashn-E-Bahaaraa",
			start: "24",
			primaryColor: "#f59504de",
			source: "https://www.youtube.com/embed/cr4Tz4JEP40",
			startPhrase: "Kehne ko...",
		},
		{
			title: "Ye Tune Kya Kiya",
			start: "87",
			primaryColor: "#D48047de",
			source: "https://www.youtube.com/embed/jcAn44985E0",
			startPhrase: "Kyu tune meri...",
		},
		{
			title: "Kabhi Jo Badal Barse",
			start: "41",
			primaryColor: "#B4457Ade",
			source: "https://www.youtube.com/embed/qH1eRWlJpsY",
			startPhrase: "Kabhi jo badal barse...",
		},
	],
	ख: [],
	ग: [],
	घ: [],
	ङ: [],
	च: [
		{
			title: "Dil me ho tum",
			start: "22",
			primaryColor: "#ffb100c2",
			source: "https://www.youtube.com/embed/byitAI7kkOM",
			startPhrase: "Chal diya...",
		},
	],
	छ: [],
	ज: [
		{
			title: "Janam Janam",
			start: "23",
			primaryColor: "#0D1B40c2",
			source: "https://www.youtube.com/embed/7KuDBVO8OY0",
			startPhrase: "Janam janam janam...",
		},
		{
			title: "Aadat",
			start: "49",
			primaryColor: "#FEC478",
			source: "https://www.youtube.com/embed/IoYy3uFXhDY",
			startPhrase: "Juda hoke bhi...",
		},
	],
	झ: [],
	ञ: [],
	ट: [],
	ठ: [],
	ड: [],
	ढ: [],
	ण: [],
	त: [
		{
			title: "Deewana kar raha hai",
			start: "33",
			primaryColor: "#0037ffc2",
			source: "https://www.youtube.com/embed/X3DWuM-a63I",
			startPhrase: "Teri bahoon...",
		},
		{
			title: "Mera mann kehne laga",
			start: "25",
			primaryColor: "#235bafde",
			source: "https://www.youtube.com/embed/wQDx6L-t-mk",
			startPhrase: "Tujhse hi to...",
		},
		{
			title: "Kaun Tujhe",
			start: "18",
			primaryColor: "#784606de",
			source: "https://www.youtube.com/embed/ZVyA_8rd1Ko",
			startPhrase: "Tu aata hai...",
		},
		{
			title: "Main Agar Kahoon",
			start: "43",
			primaryColor: "#7140bea8",
			source: "https://www.youtube.com/embed/8PEqEh1lnNE",
			startPhrase: "Tumko paaya hai...",
		},
		{
			title: "Tu Hi Meri Shab Hai",
			start: "33",
			primaryColor: "#FCD86Fa8",
			source: "https://www.youtube.com/embed/WdD0ai9cloI",
			startPhrase: "Tu hi meri...",
		},
		{
			title: "Laal Ishq",
			start: "57",
			primaryColor: "#F56D3Fc2",
			source: "https://www.youtube.com/embed/Hpf1qfIlbz8",
			startPhrase: "Tujh sang bair...",
		},
		{
			title: "Dil me chhupa lunga",
			start: "23",
			primaryColor: "#005F9Bc2",
			source: "https://www.youtube.com/embed/q4lPqY4nveo",
			startPhrase: "Tere saamne...",
		},
		{
			title: "Hawayein",
			start: "22",
			primaryColor: "#F77D70c2",
			source: "https://www.youtube.com/embed/2TcOnvGsb-k",
			startPhrase: "Tujko mai rakh lu...",
		},
		{
			title: "Tere Bin",
			start: "17",
			primaryColor: "#9E1104",
			source: "https://www.youtube.com/embed/7jbqQi5XSP4	",
			startPhrase: "Tere bin main yu...",
		},
	],
	थ: [],
	द: [
		{
			title: "Dil Ibaadat",
			start: "14",
			primaryColor: "#D83936c2",
			source: "https://www.youtube.com/embed/t7Svszhn1HQ",
			startPhrase: "Dil ibaadat kar...",
		},
		{
			title: "Aadat Original",
			start: "69",
			primaryColor: "#425F44",
			source: "https://www.youtube.com/embed/-MzYz44FWxI",
			startPhrase: "Door jitna bhi tum...",
		},
	],
	ध: [
		{
			title: "Saibo",
			start: "46",
			primaryColor: "#0071d1c2",
			source: "https://www.youtube.com/embed/JeiZTnRfrbM",
			startPhrase: "Dheere dheere...",
		},
		{
			title: "Bol Na Halke Halke",
			start: "20",
			primaryColor: "#7A91A0c2",
			source: "https://www.youtube.com/embed/D49nMgP7Vzc",
			startPhrase: "Dhaage tod lao...",
		},
	],
	न: [],
	प: [
		{
			title: "Peen Loon",
			start: "33",
			primaryColor: "#ccff00c2",
			source: "https://www.youtube.com/embed/FYHKeHYlVA4",
			startPhrase: "Peen loon...",
		},
		{
			title: "Pani Da Rang",
			start: "21",
			primaryColor: "#00bed1c2",
			source: "https://www.youtube.com/embed/Bwscs-o-4jI",
			startPhrase: "Pani da...",
		},
		{
			title: "Pehli Nazar Mein",
			start: "17",
			primaryColor: "#313C83c2",
			source: "https://www.youtube.com/embed/JWd2x6Q5TPw",
			startPhrase: "Pehli nazar mein...",
		},
	],
	फ: [],
	ब: [
		{
			title: "Bekhayali",
			start: "29",
			primaryColor: "#B12D2Ac2",
			source: "https://www.youtube.com/embed/HTQ2pSM49d",
			startPhrase: "Bekhayali mein...",
		},
		{
			title: "Baatein Ye Kabhi Na",
			start: "21",
			primaryColor: "#841F1Dc2",
			source: "https://www.youtube.com/embed/ec_otQSSz0c",
			startPhrase: "Baatein ye kabhi na...",
		},
	],
	भ: [],
	म: [
		{
			title: "Tum Tak",
			start: "18",
			primaryColor: "#f5045dde",
			source: "https://www.youtube.com/embed/Wq1zDZ81YhU",
			startPhrase: "Meri har...",
		},
		{
			title: "Maula Mere Maula",
			start: "48",
			primaryColor: "#37877Fa8",
			source: "https://www.youtube.com/embed/CvcKtsgKiTo",
			startPhrase: "Maula mere...",
		},
		{
			title: "Sawan aaya hai",
			start: "10",
			primaryColor: "#37877Fa8",
			source: "https://www.youtube.com/embed/LTl0QBlqvBA",
			startPhrase: "Mohabaat barsa dena...",
		},
		{
			title: "Muskurane",
			start: "21",
			primaryColor: "#BA4342a8",
			source: "https://www.youtube.com/embed/rrD-IKRi9Ak",
			startPhrase: "Muskurane ki wajah...",
		},
	],
	य: [
		{
			title: "Laal Ishq",
			start: "35",
			primaryColor: "#F56D3Fc2",
			source: "https://www.youtube.com/embed/Hpf1qfIlbz8",
			startPhrase: "Ye laal ishq...",
		},
	],
	र: [],
	ल: [
		{
			title: "Labon ko",
			start: "48",
			primaryColor: "#ffbc00c2",
			source: "https://www.youtube.com/embed/12pMB_mCBOo",
			startPhrase: "Labon ko...",
		},
		{
			title: "Lahu Munh Lag Gaya",
			start: "47",
			primaryColor: "#F85985a8",
			source: "https://www.youtube.com/embed/I1T3Z53tU8o",
			startPhrase: "Lahu munh lag gaya...",
		},
	],
	व: [],
	श: [
		{
			title: "Gulabi",
			start: "15",
			primaryColor: "#ff004cc2",
			source: "https://www.youtube.com/embed/kTpyO8iwlSY",
			startPhrase: "Shaam Gulabi...",
		},
	],
	ष: [],
	स: [
		{
			title: "Mann Mera",
			start: "9",
			primaryColor: "#d5a153de",
			source: "https://www.youtube.com/embed/bC9ZAQHm1wM",
			startPhrase: "Sari raat...",
		},
		{
			title: "Sun Saathiya",
			start: "18",
			primaryColor: "#AC66BCa8",
			source: "https://www.youtube.com/embed/_NWaYjsz3qY",
			startPhrase: "Sunn saathiya...",
		},
	],
	ह: [
		{
			title: "Kalank - Title Track",
			start: "15",
			primaryColor: "#700106de",
			source: "https://www.youtube.com/embed/if7X8G9c3t0",
			startPhrase: "Hawaoon me...",
		},
		{
			title: "Hale Dil",
			start: "12",
			primaryColor: "#F2443Ea8",
			source: "https://www.youtube.com/embed/BLNHOgy_HCI",
			startPhrase: "Hai kaash...",
		},
	],
	क्ष: [],
	त्र: [],
	ज्ञ: [],
	अ: [
		{
			title: "Ajab si",
			start: "8",
			primaryColor: "#850062c2",
			source: "https://www.youtube.com/embed/bdS6OoH1W2A",
			startPhrase: "Aankoon me teri...",
		},
		{
			title: "Maula Mere Maula",
			start: "78",
			primaryColor: "#37877Fa8",
			source: "https://www.youtube.com/embed/CvcKtsgKiTo",
			startPhrase: "Aankhen teri...",
		},
		{
			title: "Bol Na Halke Halke",
			start: "25",
			primaryColor: "#001523c2",
			source: "https://www.youtube.com/embed/yyYpmJx8zuU",
			startPhrase: "O re piya...",
		},
		{
			title: "Ang Laga De",
			start: "19",
			primaryColor: "#E3AA35a8",
			source: "https://www.youtube.com/embed/zDYcbUIObjU",
			startPhrase: "Ang laga de re...",
		},
		{
			title: "Dil me chhupa lunga",
			start: "61",
			primaryColor: "#005F9Bc2",
			source: "https://www.youtube.com/embed/q4lPqY4nveo",
			startPhrase: "Aise na mujhe...",
		},
	],
	उ: [],
	इ: [
		{
			title: "In Dino",
			start: "40",
			primaryColor: "#ff0000c2",
			source: "https://www.youtube.com/embed/tYHrT837H0M",
			startPhrase: "In dino...",
		},
		{
			title: "Mast Magan",
			start: "0",
			primaryColor: "#FCC33Ea8",
			source: "https://www.youtube.com/embed/InD68CDGT9Q",
			startPhrase: "Ishq ki dhunni...",
		},
	],
	ए: [],
	ऐ: [],
};
