export const alphabets = [
	"क",
	"ख",
	"ग",
	"घ",
	"ङ",
	"च",
	"छ",
	"ज",
	"झ",
	"ञ",
	"ट",
	"ठ",
	"ड",
	"ढ",
	"ण",
	"त",
	"थ",
	"द",
	"ध",
	"न",
	"प",
	"फ",
	"ब",
	"भ",
	"म",
	"य",
	"र",
	"ल",
	"व",
	"श",
	"ष",
	"स",
	"ह",
	"क्ष",
	"त्र",
	"ज्ञ",
	"अ",
	"उ",
	"इ",
	"ए",
	"ऐ",
];

export const songs = {
	क: [
		{
			title: "Wajah tum ho",
			start: "27",
			primaryColor: "#ff0000c2",
			source: "https://www.youtube.com/embed/UF9kvy51_F0",
			startPhrase: "Kaise kahu...",
		},
		{
			title: "Kya mujhe pyaar hai",
			start: "39",
			primaryColor: "#ff9900c2",
			source: "https://www.youtube.com/embed/XPu9ZE4Onzc",
			startPhrase: "Kyu ajj kal...",
		},
		{
			title: "Jashn-E-Bahaaraa",
			start: "24",
			primaryColor: "#f59504de",
			source: "https://www.youtube.com/embed/cr4Tz4JEP40",
			startPhrase: "Kehne ko...",
		},
	],
	ख: [],
	ग: [],
	घ: [],
	ङ: [],
	च: [
		{
			title: "Dil me ho tum",
			start: "22",
			primaryColor: "#ffb100c2",
			source: "https://www.youtube.com/embed/byitAI7kkOM",
			startPhrase: "Chal diya...",
		},
	],
	छ: [],
	ज: [],
	झ: [],
	ञ: [],
	ट: [],
	ठ: [],
	ड: [],
	ढ: [],
	ण: [],
	त: [
		{
			title: "Deewana kar raha hai",
			start: "33",
			primaryColor: "#0037ffc2",
			source: "https://www.youtube.com/embed/X3DWuM-a63I",
			startPhrase: "Teri bahoon...",
		},
		{
			title: "Mera mann kehne laga",
			start: "25",
			primaryColor: "#235bafde",
			source: "https://www.youtube.com/embed/wQDx6L-t-mk",
			startPhrase: "Tujhse hi to...",
		},
		{
			title: "Kaun Tujhe",
			start: "18",
			primaryColor: "#784606de",
			source: "https://www.youtube.com/embed/ZVyA_8rd1Ko",
			startPhrase: "Tu aata hai...",
		},
	],
	थ: [],
	द: [],
	ध: [
		{
			title: "Saibo",
			start: "46",
			primaryColor: "#0071d1c2",
			source: "https://www.youtube.com/embed/JeiZTnRfrbM",
			startPhrase: "Dheere dheere...",
		},
	],
	न: [],
	प: [
		{
			title: "Peen Loon",
			start: "33",
			primaryColor: "#ccff00c2",
			source: "https://www.youtube.com/embed/FYHKeHYlVA4",
			startPhrase: "Peen loon...",
		},
		{
			title: "Pani Da Rang",
			start: "21",
			primaryColor: "#00bed1c2",
			source: "https://www.youtube.com/embed/Bwscs-o-4jI",
			startPhrase: "Pani da...",
		},
	],
	फ: [],
	ब: [],
	भ: [],
	म: [
		{
			title: "Tum Tak",
			start: "18",
			primaryColor: "#f5045dde",
			source: "https://www.youtube.com/embed/Wq1zDZ81YhU",
			startPhrase: "Meri har...",
		},
	],
	य: [],
	र: [],
	ल: [
		{
			title: "Labon ko",
			start: "48",
			primaryColor: "#ffbc00c2",
			source: "https://www.youtube.com/embed/12pMB_mCBOo",
			startPhrase: "Labon ko...",
		},
	],
	व: [],
	श: [
		{
			title: "Gulabi",
			start: "15",
			primaryColor: "#ff004cc2",
			source: "https://www.youtube.com/embed/kTpyO8iwlSY",
			startPhrase: "Shaam Gulabi...",
		},
	],
	ष: [],
	स: [
		{
			title: "Mann Mera",
			start: "9",
			primaryColor: "#d5a153de",
			source: "https://www.youtube.com/embed/bC9ZAQHm1wM",
			startPhrase: "Sari raat...",
		},
	],
	ह: [
		{
			title: "Kalank - Title Track",
			start: "15",
			primaryColor: "#700106de",
			source: "https://www.youtube.com/embed/if7X8G9c3t0",
			startPhrase: "Hawaoon me...",
		},
	],
	क्ष: [],
	त्र: [],
	ज्ञ: [],
	अ: [
		{
			title: "Ajab si",
			start: "8",
			primaryColor: "#850062c2",
			source: "https://www.youtube.com/embed/bdS6OoH1W2A",
			startPhrase: "Aankoon me teri...",
		},
	],
	उ: [],
	इ: [
		{
			title: "In Dino",
			start: "40",
			primaryColor: "#ff0000c2",
			source: "https://www.youtube.com/embed/tYHrT837H0M",
			startPhrase: "In dino...",
		},
	],
	ए: [],
	ऐ: [],
};
